### ISSUE TITLE
Permitir reutilização de um item já inserido no ListError

### ISSUE THREAD

**Issue by Arthur-Henrique** [laboratoriobridge/validation#35]
Atualmente o comportamento do método *ListErrorImpl.itemError(int index)* é o de criar um novo FormError e inserí-lo na determinada posição da lista, ao invés de, como acontece no *FormErrorImpl.formError(MetaField<?>)*, primeiro verificar se a posição já estava preenchida para então devolver o objeto lá presente ao invés de sobreescrevê-lo.

Evoluindo a validação do [MeuBridge](https://github.com/laboratoriobridge/meu-bridge) aponto essa proposta de modificação.

**Comment by MaoRodriguesJ** [comment]
Fechada em https://github.com/laboratoriobridge/validation/pull/36
