### ISSUE TITLE
(13) Automatizar o processo de release 

### ISSUE THREAD

**Issue by zDudaHang** [laboratoriobridge/validation#55]
Criar um documento contendo o passo a passo de como deve ser feito o processo de realease.

Observação: os demais item desta tarefa serão implementados em issues separadas:
- #58 ;
- #59 ;
- Issue [7965](https://github.com/laboratoriobridge/pec/issues/7965).

Documento (apenas acessível para o pessoal do Bridge): https://docs.google.com/document/d/1oW3jHMa94UxtT9Op4lgj0SB8upEZYqvhFXhTXdRtNZE/edit?usp=sharing

**Comment by lucasjoao** [comment]
@zDudaHang fiz alguns comentários no documento, favor verificar lá

**Comment by lucasjoao** [comment]
Boa Duda! :rocket: 

PS: revisei o documento e tudo certinho, continuação será feita em issues futuras conforme descrição dessa aqui \o/
